### ISSUE TITLE
Reformatting the dataset

### ISSUE THREAD

**Issue by rtk29** [UM-ARM-Lab/Efficient-Eng-2-LTL#3]
Hi,

How was the dataset reformatted and moved to the folder "run/semantic_parsing_with_constrained_lm/domains/ltl/data"? Was it done manually ?

**Comment by Jiayi-Pan** [comment]
Thank you for your interests in this project! Could you share more details about the hardware and system environment you're using? 

It looks to be a straightforward error related to the tensor being on the wrong device. You might be able to quickly fix this by adding `topk_eligible_logprobs.indices.to('cuda')` before the line causing the error."

**Comment by Jiayi-Pan** [comment]
Hi it is done half manually with a sketchy script.
