### ISSUE TITLE
Runtime error in inference

### ISSUE THREAD

**Issue by HRItdy** [UM-ARM-Lab/Efficient-Eng-2-LTL#5]
Hi, thanks for the excellent work.

When I tried to do the inference as stated in the readme.txt, I entered:

`export PRETRAINED_MODEL_DIR=huggingface_models/bart-large
export TRAINED_MODEL_DIR=trained_models/

DOMAIN=pick-syn-aug
python -m semantic_parsing_with_constrained_lm.run_exp \
--config-name semantic_parsing_with_constrained_lm.configs.ltl_config \
--log-dir logs/ \                                                      
--model Bart \
--eval-split test-full \
--exp-names "ltl_Bart_test-full_${DOMAIN}_constrained_utterance_train-0"
Entire model to GPU 0`

Then a runtime error raised:

`Last test_datum: FullDatum(dialogue_id='eval-0', turn_part_index=None, agent_context=None, natural='move the arm to the block and pick it up next placing it in the bin and coming back to pick up the next block', canonical='globally ( and ( until ( scan , not ( any cubes ) ) , finally ( any cubes ) ) )') in experiment ltl_Bart_test-full_pick-syn-aug_constrained_utterance_train-0
Traceback (most recent call last):
  File "/home/tiandy/Efficient-Eng-2-LTL/run/semantic_parsing_with_constrained_lm/model.py", line 366, in predict
    results = await beam_search(
  File "/home/tiandy/Efficient-Eng-2-LTL/run/semantic_parsing_with_constrained_lm/search.py", line 388, in beam_search
    for node, per_node_expansion in await asyncio.gather(
  File "/home/tiandy/Efficient-Eng-2-LTL/run/semantic_parsing_with_constrained_lm/search.py", line 381, in expand
    expansions = await problem.expand(node)
  File "/home/tiandy/Efficient-Eng-2-LTL/run/semantic_parsing_with_constrained_lm/search.py", line 219, in expand
    indices[topk_eligible_logprobs.indices],
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)`

I tried several solutions in stackoverflow but they didn't work. Do you have any suggestion about this? Any idea is appreciated. Thanks!

**Comment by Jiayi-Pan** [comment]
Does your server have NVidia GPUs? It looks to be a straightforward error related to the tensor being on the wrong device. You might be able to quickly fix this by moving the data to "cuda" before the line causing the error.

**Comment by HRItdy** [comment]
Thanks for your reply! I have two 3090 GPU and the training phase is good.
I will try to move the data to cuda. Thanks again!

Regards.

Jiayi Pan ***@***.***> 于2023年9月19日周二 12:04写道：
